# Robot parameters 
tcp_acc: 0.05
tcp_vel: 0.05

# Gripper parameters
tcp2fingertip: 0.28118 #0.275 # distance from tcp to gripper fingertip
gripper_speed: 0.1 # value between 0.013 and 0.100
gripper_force: 10 # value between 0 and 100

# Object dimension
object_thickness: 0.0057 #0.01 # object thickness in meters
object_length: 0.023 # object length in meters

# Initial configuration
delta_0: 0.022 #0.0425 # distance from fingertip to object tip within gripper
theta_0: 40

# Intermediate configuration
psi_regrasp: 38
theta_tilt: 25
tuck: 6

# Action axis
axis: [1, 0, 0]

